---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: images-url
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/spring-projects/spring-petclinic
        - name: revision
          value: "d367e2b4b41a2de899b0f438bc984a7c1c011b77"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: s2i-java-binary-build
      taskRef:
        name: s2i-java-binary-build
      runAfter:
        - maven-run
      workspaces:
        - name: binary
          workspace: shared-workspace
      params:
      - name: BUILD_NAME
        value: java-binary-build13
      - name: PATH_TYPE
        value: File
      - name: BINARY_PATH
        value: ./target
    - name: copy-image
      taskRef:
        name: skopeo-copy
      runAfter:
        - s2i-java-binary-build
      workspaces:
        - name: images-url
          workspace: images-url
      params:
      - name: srcImageURL
        value: docker://$(tasks.s2i-java-binary-build.results.image-url)
      - name: destImageURL
        value: docker://quay.io/diagarwa/java-binary-build:v1
      - name: destTLSverify
        value: "false"
