---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-test-pipeline-run
spec:
  pipelineRef:
    name: s2i-test-pipeline
  serviceAccountName: secret-service-account
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
    - name: images-url
      emptyDir: {}